name: ncdu 
adopt-info: ncdu
summary: ncdu (NCurses Disk Usage) is a curses-based version of the well-known 'du'
description: |
  ncdu (NCurses Disk Usage) is a curses-based version of the well-known 'du', and provides a fast way to see what directories are using your disk space.
  After installation, run the following commands:
  
    sudo snap connect ncdu:removable-media
    sudo snap connect ncdu:mount-observe
    sudo snap connect ncdu:system-backup
    
    
base: core18
grade: stable 
confinement: strict 
license: MIT

architectures:
- build-on: amd64
- build-on: i386

apps:
  ncdu:
    aliases: 
      - ncdu
    command: ncdu
    plugs:
      - home
      - removable-media
      - mount-observe
      - system-backup # testing 
     
parts: 
  ncdu:
    source: https://code.blicky.net/yorhel/ncdu.git
    source-type: git
    plugin: autotools
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
    
    build-packages:
      - perl
      - autoconf
      - pkg-config
      - libncurses5-dev
      
    configflags: 
      - "--prefix=/usr"
